{% set name = "respx" %}
{% set version = "0.19.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3d210bb4de0ccc4c5afabeb87c3c1b03b3765a9c1a73eb042a07bb18ac33705

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - httpx >=0.21
    - python >=3.6

test:
  imports:
    - respx

about:
  home: https://lundberg.github.io/respx
  summary: A utility for mocking out the Python HTTPX library.
  license: BSD-3-Clause
  license_file: LICENSE.md
  dev_url: https://github.com/lundberg/respx
  doc_url: https://lundberg.github.io/respx

extra:
  recipe-maintainers:
    - synapticarbors
