{% set name = "respx" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a09e15803c7450d45303520ec528794c9fd77b05984263bc83b78aabbb39413

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - httpx >=0.20
    - python >=3.6

test:
  imports:
    - respx

about:
  home: https://lundberg.github.io/respx
  summary: A utility for mocking out the Python HTTPX library.
  license: BSD-3-Clause
  license_file: LICENSE.md
  dev_url: https://github.com/lundberg/respx
  doc_url: https://lundberg.github.io/respx

extra:
  recipe-maintainers:
    - synapticarbors
